### PR TITLE
Upgrade go.mongodb.org/mongo-driver version to v1.4.2

### PR DESCRIPTION
**Pull request by bvwells**
Upgrade go.mongodb.org/mongo-driver version to v1.4.2. Version v1.0.3 has various vulnerabilities which are highlighted in various code scanners.

### CODE REVIEW

**Review by casualjim — APPROVED** [review]

**Comment by bvwells** [comment]
Thanks for the review and merge @casualjim!

**Comment by bvwells** [comment]
@casualjim do you know when you are planning to have the next patch release of this module?

**Comment by casualjim** [comment]
done

**Comment by bvwells** [comment]
Great! Many thanks @casualjim. I can roll this version out across other go-openapi modules if that is okay with you?

**Comment by casualjim** [comment]
That's fine although it's not strictly required

**Comment by bvwells** [comment]
The static analysers I am using analyse the go.sum file so even upgrading our code to the latest go-openapi/strfmt we still have go.sum entries for old versions of this module as the dependency of other go-openapi modules e.g. go-openapi/runtime.

I've noticed that there is a circular dependency between github.com/go-openapi/loads and github.com/go-openapi/analysis. Do you update this in any particular order?

**Pull request merged**
