### PR TITLE
update time.go work with mgo.v2

### PR DESCRIPTION
**Pull request by roytan883**

### CODE REVIEW

**Comment by casualjim** [comment]
Can you do the same for the other strfmts so that they all support the same tools?
Secondly the .travis.yml file needs to be updated to also get mgo for building

**Comment by GlenDC** [comment]
Hey @roytan883, how is it going with this PR?

**Comment by roytan883** [comment]
@GlenDC It works for me. But it seems can't pass the ci test. Anyway, you can just copy code and make it work if you use mgo.v2

**Comment by GlenDC** [comment]
@roytan883 in order to make your current PR work, you can do the following 2 steps:

1. fetch origin/master && rebase it into your branch
2. apply following patch:

```diff
diff --git a/.travis.yml b/.travis.yml
index 45a9a0a..a2620c3 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -8,6 +8,7 @@ install:
 - go get -u github.com/mailru/easyjson
 - go get -u github.com/go-openapi/errors
 - go get -u github.com/mitchellh/mapstructure
+- go get -u gopkg.in/mgo.v2
 script:
 - go test -v -race -cover -coverprofile=coverage.txt -covermode=atomic ./...
 after_success:
diff --git a/time.go b/time.go
index 618b89c..315952a 100644
--- a/time.go
+++ b/time.go
@@ -23,6 +23,8 @@ import (
 
 	"github.com/mailru/easyjson/jlexer"
 	"github.com/mailru/easyjson/jwriter"
+
+    "gopkg.in/mgo.v2/bson"
 )
 
 func init() {
```

Could you please also add unit tests in `time_test.go` to test your 2 added methods? It will showcase how these methods will be typically used, and it also gives some guarantees on whether or not the current implementation works.

Thanks :)

**Comment by casualjim** [comment]
superseded by #12

**Pull request closed without merging**
