### PR TITLE
Fixed isDate validation; added unittests

### LINKED ISSUE #18: IsDate validation allows values that are not valid dates
[regexp ](https://github.com/go-openapi/strfmt/blob/master/date.go#L50) used in `IsDate` function for date validation doesn't consider all the cases.
As a result it validates successfully values like `2017-12-22T01:02:03Z` which is not correct.

Following test below fails with current implementation of `IsDate`:
```
func TestDate_IsDate(t *testing.T) {
	tests := []struct {
		value string
		valid bool
	}{
		{"2017-12-22", true},
		{"2017-1-1", false},
		{"17-13-22", false},
		{"2017-02-29", false}, // not a valid date : 2017 is not the leap year
		{"2017-13-22", false},
		{"2017-12-32", false},
		{"20171-12-32", false},
		{"YYYY-MM-DD", false},
		{"20-17-2017", false},
		{"2017-12-22T01:02:03Z", false},
	}
	for _, test := range tests {
		assert.Equal(t, test.valid, IsDate(test.value), "value [%s] should be valid: [%t]", test.value, test.valid)
	}
}
```

### PR DESCRIPTION
**Pull request by krnkl**
- Fixed isDate validation
- added unittests
fixes #18

### CODE REVIEW

**Comment by kmudrick** [comment]
Stupid question - does the go-swagger project actually generate models that can _use_ this `isDate` implementation?

**Comment by casualjim** [comment]
yeah it uses that to validate dates

**Comment by kmudrick** [comment]
Hmm. If I clone master of `go-swagger` and grep for `IsDate`, I see no references to `IsDate` except in tests.

Right now, if I try to call `UnmarshalJSON()` on a wrapping model (passing it the bytes of the request body) - if there is deeply nested property with a date format, then the unmarshal call fails with a parse error, e.g. "parsing time "2016-04-35": day out of range".

**Comment by casualjim** [comment]
It registers itself here:
https://github.com/go-openapi/strfmt/blob/master/date.go#L32

it then gets called here:
https://github.com/go-openapi/strfmt/blob/HEAD/format.go#L275

which gets called by:
https://github.com/go-openapi/validate/blob/master/formats.go#L61

which the generated code calls through:
https://github.com/go-openapi/validate/blob/master/values.go#L241

**Pull request merged**
